parameters:
#    elliot_common.example.class: Elliot\CommonBundle\Example

services:
#    elliot_common.example:
#        class: %elliot_common.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
