soundgap_ca_homepage:
    pattern:  /
    defaults: { _controller: SoundGapContentAdminBundle:Default:index }

soundgapca_system_school:
    pattern:  /system/school
    defaults: { _controller: SoundGapContentAdminBundle:System:school }
soundgapca_system_school_update:
    pattern:  /system/school/{id}
    defaults: { _controller: SoundGapContentAdminBundle:System:school }
soundgapca_system_school_delete:
    pattern:  /system/school/delete/{id}
    defaults: { _controller: SoundGapContentAdminBundle:System:schoolDelete }
soundgapca_system_school_userupdate:
    pattern:  /system/user/school
    defaults: { _controller: SoundGapContentAdminBundle:System:userSchool }

soundgapca_system_app:
    pattern:  /system/app
    defaults: { _controller: SoundGapContentAdminBundle:System:app }
soundgapca_system_app_update:
    pattern:  /system/app/{id}
    defaults: { _controller: SoundGapContentAdminBundle:System:schoolApp }
soundgapca_system_app_delete:
    pattern:  /system/app/delete/{id}
    defaults: { _controller: SoundGapContentAdminBundle:System:appDelete }
soundgapca_system_app_userupdate:
    pattern:  /system/user/app
    defaults: { _controller: SoundGapContentAdminBundle:System:userApp }

soundgapca_system_schoolapp:
    pattern:  /system/schoolapp
    defaults: { _controller: SoundGapContentAdminBundle:System:schoolApp }
soundgapca_system_schoolapp_update:
    pattern:  /system/schoolapp/{id}
    defaults: { _controller: SoundGapContentAdminBundle:System:schoolApp }
soundgapca_system_schoolapp_delete:
    pattern:  /system/schoolapp/delete/{id}
    defaults: { _controller: SoundGapContentAdminBundle:System:schoolAppDelete }

soundgapca_system_apppackage:
    pattern:  /system/apppackage
    defaults: { _controller: SoundGapContentAdminBundle:System:apppackage }
soundgapca_system_apppackage_update:
    pattern:  /system/apppackage/{id}
    defaults: { _controller: SoundGapContentAdminBundle:System:apppackage }
soundgapca_system_apppackage_delete:
    pattern:  /system/apppackage/delete/{id}
    defaults: { _controller: SoundGapContentAdminBundle:System:apppackageDelete }


soundgapca_asset_character:
    pattern:  /asset/character
    defaults: { _controller: SoundGapContentAdminBundle:Asset:character }
soundgapca_asset_character_update:
    pattern:  /asset/character/{id}
    defaults: { _controller: SoundGapContentAdminBundle:Asset:character }
soundgapca_asset_character_delete:
    pattern:  /asset/character/delete/{id}
    defaults: { _controller: SoundGapContentAdminBundle:Asset:characterDelete }
soundgapca_asset:
    pattern:  /asset/asset
    defaults: { _controller: SoundGapContentAdminBundle:Asset:asset }
soundgapca_asset_update:
    pattern:  /asset/asset/{id}
    defaults: { _controller: SoundGapContentAdminBundle:Asset:asset }
soundgapca_asset_delete:
    pattern:  /asset/asset/delete/{id}
    defaults: { _controller: SoundGapContentAdminBundle:Asset:assetDelete }
soundgapca_asset_characterpose:
    pattern:  /asset/characterPose
    defaults: { _controller: SoundGapContentAdminBundle:Asset:characterPose }
soundgapca_asset_characterpose_update:
    pattern:  /asset/characterPose/{id}
    defaults: { _controller: SoundGapContentAdminBundle:Asset:characterPose }
soundgapca_asset_characterpose_delete:
    pattern:  /asset/characterPose/delete/{id}
    defaults: { _controller: SoundGapContentAdminBundle:Asset:characterPoseDelete }
soundgapca_asset_emoticon:
    pattern:  /asset/emoticon
    defaults: { _controller: SoundGapContentAdminBundle:Asset:emoticon }
soundgapca_asset_emoticon_update:
    pattern:  /asset/emoticon/{id}
    defaults: { _controller: SoundGapContentAdminBundle:Asset:emoticon }
soundgapca_asset_emoticon_delete:
    pattern:  /asset/emoticon/delete/{id}
    defaults: { _controller: SoundGapContentAdminBundle:Asset:emoticonDelete }


soundgapca_system_set_schoolappid:
    pattern:  /system/set/school/{id}
    defaults: { _controller: SoundGapContentAdminBundle:System:setSchoolAppId }

soundgapca_ground_category:
    pattern:  /ground/category
    defaults: { _controller: SoundGapContentAdminBundle:Ground:category }
soundgapca_ground_category_update:
    pattern:  /ground/category/{id}
    defaults: { _controller: SoundGapContentAdminBundle:Ground:category }
soundgapca_ground_category_delete:
    pattern:  /ground/category/delete/{id}
    defaults: { _controller: SoundGapContentAdminBundle:Ground:categoryDelete }
soundgapca_ground_grade:
    pattern:  /ground/grade/{categoryId}
    defaults: { _controller: SoundGapContentAdminBundle:Ground:grade }
soundgapca_ground_grade_delete:
    pattern:  /ground/grade/delete/{id}
    defaults: { _controller: SoundGapContentAdminBundle:Ground:gradeDelete }
soundgapca_ground_grade_update:
    pattern:  /ground/grade/{categoryId}/{id}
    defaults: { _controller: SoundGapContentAdminBundle:Ground:grade }

soundgap_ca_parts_quest:
    pattern:  /parts/quest
    defaults: { _controller: SoundGapContentAdminBundle:Parts:quest }
soundgap_ca_parts_quest_update:
    pattern:  /parts/quest/{id}
    defaults: { _controller: SoundGapContentAdminBundle:Parts:quest }
soundgap_ca_parts_quest_delete:
    pattern:  /parts/quest/delete/{id}
    defaults: { _controller: SoundGapContentAdminBundle:Parts:questDelete }

soundgap_ca_main_station:
    pattern:  /main/station
    defaults: { _controller: SoundGapContentAdminBundle:Main:station }
soundgap_ca_main_station_update:
    pattern:  /main/station/{id}
    defaults: { _controller: SoundGapContentAdminBundle:Main:station }
soundgap_ca_main_stationContent:
    pattern:  /main/stationcontent/{stationId}
    defaults: { _controller: SoundGapContentAdminBundle:Main:stationContent }
soundgap_ca_main_stationContent_update:
    pattern:  /main/stationcontent/update/{stationContentId}
    defaults: { _controller: SoundGapContentAdminBundle:Main:stationContentUpdate }
soundgap_ca_main_stationQuest:
    pattern:  /main/stationquest/{stationId}
    defaults: { _controller: SoundGapContentAdminBundle:Main:stationQuest }
soundgap_ca_main_stationQuest_add:
    pattern:  /main/stationquest/{stationQuestId}/{questId}
    defaults: { _controller: SoundGapContentAdminBundle:Main:stationQuestAdd }
soundgap_ca_main_stationQuest_remove:
    pattern:  /main/stationquestRemove/{stationQuestId}/{questId}
    defaults: { _controller: SoundGapContentAdminBundle:Main:stationQuestRemove }
soundgap_ca_main_stationPath:
    pattern:  /main/stationPath/{gradeId}/{fromId}/{toId}
    defaults: { _controller: SoundGapContentAdminBundle:Main:stationPath, gradeId:null, fromId:null, toId:null }

soundgap_ca_main_station_delete:
    pattern:  /main/station/delete/{id}
    defaults: { _controller: SoundGapContentAdminBundle:Main:stationDelete }
soundgap_ca_main_stationContent_delete:
    pattern:  /main/stationcontent/delete/{id}
    defaults: { _controller: SoundGapContentAdminBundle:Main:stationContentDelete }
soundgap_ca_main_stationQuest_delete:
    pattern:  /main/stationquest/delete/{id}
    defaults: { _controller: SoundGapContentAdminBundle:Main:stationQuestDelete }
soundgap_ca_main_stationPath_remove:
    pattern:  /main/stationPathRemove/{fromId}/{toId}
    defaults: { _controller: SoundGapContentAdminBundle:Main:stationPathRemove }

