sound_gap_www:
    pattern: /
    defaults: { _controller: SoundGapContentAdminBundle:Default:www }

sound_gap_user:
    resource: "@SoundGapUserBundle/Resources/config/routing.yml"
    prefix:   /

sound_gap_app_api:
    resource: "@SoundGapAppApiBundle/Resources/config/routing.yml"
    prefix:   /api

sound_gap_content_admin:
    resource: "@SoundGapContentAdminBundle/Resources/config/routing.yml"
    prefix:   /ca

## fos
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
