<?php

namespace SoundGap\ContentAdminBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * PointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointRepository extends DocumentRepository
{
}