soundgap_app_api_homepage:
    pattern:  /
    defaults: { _controller: SoundGapAppApiBundle:Default:index }
soundgap_app_api_test:
    pattern:  /test
    defaults: { _controller: SoundGapAppApiBundle:User:index }

soundgap_theory_app_api_version:
    pattern:  /version
    defaults: { _controller: SoundGapAppApiBundle:Version:getVersion, _format: json }

# authentication
soundgap_user_api_signup:
    pattern:  /user/signup
    defaults: { _controller: SoundGapAppApiBundle:User:signup, _format: json }
soundgap_user_api_login:
    pattern:  /user/login
    defaults: { _controller: SoundGapAppApiBundle:User:login, _format: json }
soundgap_user_api_resetpassword:
    pattern:  /user/resetPassword
    defaults: { _controller: SoundGapAppApiBundle:User:resetPassword, _format: json }
