parameters:
#    sound_gap_app_api.example.class: SoundGap\AppApiBundle\Example

services:
#    sound_gap_app_api.example:
#        class: %sound_gap_app_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
